config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  # get "restaurants" => "restaurants#index"
  # get "restaurants/:id" => "restaurants#show"
  # get "restaurants/:new" => "restaurants#new"
  # post "restaurants" => "restaurants#create"
  # get "restaurants/:id/edit" => "restaurants#edit"
  # patch "restaurants/:id" => "restaurants#update"
  # delete "restaurants/:id" => "restaurants#restroy"

  resources :restaurants do

    resources :reviews, only: [:new, :create]

    collection do
      get :top
    end

    member do
      # get :chef # /restaurant/:id/chef par exemple
    end
  end
  resources :reviews, only: [:destroy]
  resources :contacts, only: [:new, :create]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    can :manage, :all
    if user.superadmin_role?
          can :manage, :all
          can :access, :rails_admin       # only allow admin users to access Rails Admin
          can :manage, :dashboard         # allow access to dashboard
    end
    if user.supervisor_role?
          can :manage, User
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact <  MailForm::Base
  attribute :name, validate => true
  attribute :email, validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, validate => true
  attribute :nickname, :captcha => true

  def headers
    {
      :subject => "Contact Form",
      :to => "gavefaim@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  validates :name, presence: true
  validates :title, presence: true
  validates :description, presence: true
  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews

  has_many_attached :images
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, uniqueness: true
  validates :password, length: { in: 6..20 }
  GENDER = ["Homme", "Femme"]

  has_one_attached :photo
  has_many :restaurants
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.fetch(:contact, {})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :top]
  skip_before_action :authenticate_user!, only: [:index]

  def top
    @restaurants = Restaurant.where(rating: 9..10)
  end

  def index
    @restaurants = Restaurant.all
  end

  def show

  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    @restaurant.user = current_user

    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :title, :address, :description, :descriptionDeux, :rating, :style, images: [], photos: [])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def update

  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    restaurant = Restaurant.find(params[:restaurant_id])

    @review.restaurant = restaurant
    @review.user = current_user
    if @review.save
     redirect_to restaurant_path(restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

  def update
    @user.update(user_params)
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :gender, :password, :photos)
  end

  def set_restaurant
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/create.html.erb
<div class="contact" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.pexels.com/photos/3815830/pexels-photo-3815830.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940);">
  <div class="container">
    <h1>Merci, nous te répondrons au plus vite</h1>
    <div class="lignes">
    </div>
    <h3>Très bonne journée</h3>

    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="contact" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.pexels.com/photos/1415734/pexels-photo-1415734.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260); background-size: cover">
  <div class="blank"></div>
  <div class="container">
    <h1>N'hesitez pas à nous <strong>contacter</strong></h1>
    <div class="lignes"></div>
      <h4>Ici, pas de formulaire avec 10 champs à remplir.
      Si vous avez des questions, des demandes particuliaires ou si vous voulez juste
      échanger avec nous, contactez-nous par mail à <br>gavefaim@gmail.com</h4>

      <h5>Merci 🙏</h5>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GaveFaim</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <!-- <p class="notice"><%= notice %></p> -->
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
  <footer>
    <%= render 'shared/footer' %>
  </footer>

</html>

app/views/pages/about.html.erb
<div class="about" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1516824237444-09453e0027ed?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80); background-size: cover">
  <div class="container">
    <h1>She's the <strong>fork</strong> , he's the <strong>knife</strong> !</h1>
    <div class="lignes">
    </div>
    <div class="grid">

      <p>Bonjour, je m’appelle Emilie et lui c'est Jérôme, nous avons 32 ans chacun et une appétence commune pour les <em>bonnes adresses
        culinaires Bordelaises</em> (ainsi qu’un nom de famille commun, depuis peu !). <br>
        Depuis maintenant 3 ans nous nous invitons, chacun notre tour, chaque mois, dans un « <em>resto surprise</em> ».
        Cela nous vaut bien quelques heures de recherche (Instagram, The Fork, Tripadvisor,
        entre autres !) pour trouver la prochaine adresse qui déboite
        et une « date night » où se régaler, à deux ! <br>
        <br>
        En plus d'aimer manger à sa faim, voir gavé, Jérôme, est designer. Les formes et les couleurs d'un dressage ne le laissent pas indifférent.
        Il est aussi devenu <em>développeur web</em> pendant le confinement.
        De ce fait, il lie ses deux talents pour nous construire ce site et <em>partager nos découvertes</em>.
        </p>

      <div class="pic">
        <%= cl_image_tag("cu71gw24mvpalybr8beq11dj7nq6") %>
      </div>
      <div class="pic">
        <%= cl_image_tag("s0rajfkgbc37rym8897s4bb4jd24") %>
      </div>
        <p>
        Emilie, c'est une professionnelle du <em>vin</em> et une <em>épicurienne</em> depuis toujours.
        Cela fait maintenant des années qu’elle déniche des <em>adresses "pépites"</em> dans la région
        et les partagent allégrement avec se amis, connaissances et collègues.
        Ce projet est donc né entre nous de manière très évidente et continuera à évoluer selon vos retours.
        Nous avons confectionné une grille d'évaluation pour nous aider à noter chaque adresse
        de la manière la plus « juste » possible à nos yeux, en tenant en compte des critères
        de service, <em>rapport qualité-prix</em>, carte des vins, cadre, propreté, originalité, accessibilité
        et le choix de vaisselle et verrerie. Nous notons chacun le restaurant de notre côté
        et faisons une moyenne des deux notes. Nous accompagnons cette note de nos <em>commentaires</em>
        pour vous faire un retour <em>le plus complet possible</em>.
        En espérant que cela vous plaise et puisse peut-être vous aider à choisir votre
        prochain restaurant à deux ou entres amis…
        N’hésitez pas à nous faire part des vos retours et/ou questions.
        </p>

    </div>
    <h2>Merci pour votre <strong>visite</strong> et bonne lecture !</h2>
    <div class="bouton">
    <a class="btn" <%= link_to "Visiter", restaurants_path %></a>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.pexels.com/photos/1415734/pexels-photo-1415734.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260);">
  <div class="container">
    <div class="contact">

      <p></p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80);">
  <div class="container">
    <div class="prez">
      <div class="logo"><%= image_tag "logo-blc.png" %></div>
      <p>
      <span id="banner-typed-text"></span>
      </p>
      <!-- <p>Deux amoureux de la gastronomie vous présentent leurs découvertes culinaires bordelaises</p> -->
      <% if user_signed_in? %>
        <a class="btn btn-flat" <%= link_to "Bienvenue #{current_user.name}", restaurants_path %> </a>
      <% else %>
        <a class="btn btn-flat" <%= link_to "Visiter", restaurants_path %> </a>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<div class="banner2" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.6)), url(https://images.unsplash.com/photo-1558900493-3b6cc10d7aff?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80); background-size: cover">


  <!-- ---------3 last-------------- -->

  <div class="container">
    <div class="intro">
      <h1>Nos dernières <strong>découvertes</strong></h1>
      <p>Chaque mois un nouveau restaurant se rajoute à notre liste</p>
      <% if current_user.nil? %>
      <% elsif current_user.superadmin_role? || current_user.supervisor_role? %>
        <%= link_to "Nouveau post", new_restaurant_path %>
      <% end %>
    </div>

    <div class="cards">
    <% @restaurants.last(3).each do |restaurant| %>
      <div class="card-trip">
        <%= cl_image_tag restaurant.images[0].key %>
        <div class="card-trip-infos">
          <div>
            <h2><%= restaurant.name %></h2>
            <p><%= restaurant.address %></p>
            <p><%= restaurant.style %></p>
            <div class="hl1line"></div>
            <h3><%= restaurant.description[0, 40] %>...</h3>
            <a class="btn btn-flat" <%= link_to "Lire la suite", restaurant_path(restaurant) %></a>
            <% if current_user.nil? %>
            <% elsif current_user.superadmin_role? || current_user.supervisor_role? %>
              <a class="btn btn-flat"<%= link_to "Supprimer", restaurant_path(restaurant), method: :delete, data: {
                confirm: "C'est ton dernier mot?" } %></a>
            <% end %>
          </div>
          <h4 class="card-trip-pricing"><%= restaurant.rating %>/10</h4>
          <div class="card-trip-user avatar-bordered">

          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
    <!-- -------top 3----------- -->
  <div class="top3" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1578508053827-fe06d4dc2457?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1534&q=80);">
    <div class="container">
      <div class="intro">
        <h1>Notre <strong>top</strong> 3</h1>
        <p>Ne manquez pas nos 3 restaurants préférés du moment !</p>
      </div>

      <div class="cards">
      <% @restaurants.where(rating: 9..10).last(3).each do |restaurant| %>
        <div class="card-trip">
          <%= cl_image_tag restaurant.images[0].key %>
          <div class="card-trip-infos">
            <div>
              <h2><%= restaurant.name %></h2>
              <p><%= restaurant.address %></p>
              <p><%= restaurant.style %></p>
              <div class="hl1line"></div>
              <h3><%= restaurant.description[0, 40] %>...</h3>
              <a class="btn btn-flat" <%= link_to "Lire la suite", restaurant_path(restaurant) %></a>
              <% if current_user.nil? %>
              <% elsif current_user.superadmin_role? || current_user.supervisor_role? %>
                <a class="btn btn-flat"<%= link_to "Supprimer", restaurant_path(restaurant), method: :delete, data: {
                confirm: "C'est ton dernier mot?" } %></a>
            <% end %>
            </div>
            <h4 class="card-trip-pricing"><%= restaurant.rating %>/10</h4>
            <img src="https://pbs.twimg.com/profile_images/3252299897/a88b1777917d9d1a07ccfd8fb09979f2_400x400.jpeg" class="card-trip-user avatar-bordered" />
          </div>
        </div>
      <% end %>
    </div>
    </div>
  </div>

    <!-- -------list de tous les restau----------- -->
  <div class="container">
    <div class="intro">
      <h1>Où sommes nous allés ?</h1>
      <p>Voilà la liste des <strong>restaurants</strong> où nous sommes allés</p>
    </div>

    <div class="cards">
    <% @restaurants.each do |restaurant| %>
      <div class="card-trip">
        <%= cl_image_tag restaurant.images[0].key %>
        <div class="card-trip-infos">
          <div>
            <h2><%= restaurant.name %></h2>
            <p><%= restaurant.address %></p>
            <p><%= restaurant.style %></p>
            <div class="hl1line"></div>
            <h3><%= restaurant.description[0, 40] %>...</h3>
            <a class="btn btn-flat" <%= link_to "Lire la suite", restaurant_path(restaurant) %></a>
            <% if current_user.nil? %>
            <% elsif current_user.superadmin_role? || current_user.supervisor_role? %>
              <a class="btn btn-flat"<%= link_to "Supprimer", restaurant_path(restaurant), method: :delete, data: {
                confirm: "C'est ton dernier mot?" } %></a>
            <% end %>
          </div>
          <h4 class="card-trip-pricing"><%= restaurant.rating %>/10</h4>
          <img src="https://pbs.twimg.com/profile_images/3252299897/a88b1777917d9d1a07ccfd8fb09979f2_400x400.jpeg" class="card-trip-user avatar-bordered" />
        </div>
      </div>
    <% end %>
    </div>
  </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<!-----------Banner------------>

<div class="bannershow jarallax" data-jarallax data-speed=".8" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @restaurant.images[0].key %>);">
    <div class="row">
      <div class="col-6 offset-3">
        <div class="container">
          <div class="intro">
            <h1><%= @restaurant.name %></h1>
            <p><%= @restaurant.style %></p>
            <p><%= @restaurant.address %></p>
          </div>
        </div>
      </div>
    </div>
</div>

<div class="container">
  <div class="postTitle">
    <h2>" <%= @restaurant.title %> "</h2>
    <div class="daterating">
      <p>Article publié le <%= @restaurant.created_at.strftime("%d-%m-%Y à %k:%M") %> par <%= @restaurant.user.name %></p>
      <h4><%= @restaurant.rating %>/10</h4>
    </div>

    <hr>
  </div>

      <!-----------descritpion------------>

  <div class="container">
    <div class="gridShowA">
      <div class="presentation">


        <p><%= @restaurant.description %></p>
  <!--       <p><%= cl_image_tag @restaurant.images[0].key %></p>
   -->
      </div>
        <!-----------Carousel------------>
      <div class="slider">
        <div id="carouselExampleControlsA" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% @restaurant.images.each do |image| %>
              <% if image == @restaurant.images.first %>
                <div class="carousel-item active">
              <% else %>
                <div class="carousel-item">
              <% end %>
                <%= cl_image_tag image.key, class: "d-block w-100" %>
              </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControlsA" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControlsA" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
    <div class="gridShowB">
      <div class="slider">
        <div id="carouselExampleControlsB" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% @restaurant.images.each do |image| %>
              <% if image == @restaurant.images.last %>
                <div class="carousel-item active">
              <% else %>
                <div class="carousel-item">
              <% end %>
                <%= cl_image_tag image.key, class: "d-block w-100" %>
              </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControlsB" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControlsB" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <div class="presentation">
        <p><%= @restaurant.descriptionDeux %></p>
      </div>
    </div>
  </div>

<hr>
<!-----------commentaires------------>
      <div class="review">
        <h2>Ce que vous en pensez</h2>
        <p>Si vous avez des commentaires ou des demandes particulières</p>
        <br>
        <div class="bouton">
        <a class="btn" <%= link_to "poster un commentaire", new_restaurant_review_path(@restaurant)  %></a>
        </div>
        <br>
        <ul class="list-group">
            <% @restaurant.reviews.each do |review| %>

              <li class="list-group-item">
                <% if review.user.photo.attached? %>
                  <%= cl_image_tag "#{review.user.photo.key}", crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% else %>
                   <%= image_tag review.user.gender == "Homme" ? "avatar_homme.jpg" : "avatar_femme.png", width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% end %>
                <br>
                <h8><%= review.user.name %></h8>
                <p>le <%= review.created_at.strftime("%d-%m-%Y à %k:%M") %></p>
                <h5><%= review.content %></h5>
                <% if current_user || current_user.superadmin_role? %>
                <%= link_to "Supprimer", review_path(review), method: :delete, data: { confirm: "Are you sure?" }  %>
                <% end %>
             </li>
            <% end %>
        </ul>
      </div>



      <br>
      <% if current_user.nil? %>
      <% elsif current_user.superadmin_role? || current_user.supervisor_role? %>
        <%= link_to "Modifier l'article", edit_restaurant_path(@restaurant) %>
      <% end %>
      <%=  %>



</div>

app/views/restaurants/top.html.erb
<h1>Nos meilleurs restaurants</h1>


 <% @restaurants.each do |restaurant| %>
  <h2><%= restaurant.name %></h2>
  <p><%= @restaurant.description %></p>
  <p><%= restaurant.address %></p>
  <p><%= restaurant.rating %></p>
  <p><%= restaurant.style %></p>
  <%= link_to "Voir", restaurant_path(restaurant)  %>
  <br>
  <%= link_to "Supprimer", restaurant_path(restaurant), method: :delete, data: {
    confirm: "C'est ton dernier mot?" } %>
 <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-blc.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Les restaurants", restaurants_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Qui sommes nous ?", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", new_contact_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag "#{current_user.photo.key}", width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
             <%= image_tag current_user.gender == "Homme" ? "avatar_homme.jpg" : "avatar_femme.png", width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Editer", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>